# Generated by Django 4.2.1 on 2023-05-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.UUIDField()),
                ('content', models.TextField()),
                ('chatbot_name', models.CharField(default='Marla', max_length=255)),
                ('business_name', models.CharField(default='Business', max_length=255)),
            ],
        ),
    ]
