# Generated by Django 4.2.1 on 2023-05-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='tone_of_voice',
            field=models.CharField(default='polite & curteous', max_length=255),
        ),
    ]
